# ???? ??????
spring.datasource.url=jdbc:postgresql://localhost:5432/hogwarts
spring.datasource.username=student
spring.datasource.password=chocolatefrog

# Hibernate (?????? ?????????)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Liquibase
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml

# ???? ?????????? (?? ?????????)
server.port=8080